# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 05:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.DecimalField(decimal_places=100, max_digits=100)),
                ('to_currency', models.DecimalField(decimal_places=100, max_digits=100)),
                ('amount', models.DecimalField(decimal_places=100, max_digits=100)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('transaction_to', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
