# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0002_transaction_transaction_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_currency',
            field=models.CharField(max_length=10),
        ),
    ]
