# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0003_auto_20180108_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.CharField(max_length=200),
        ),
    ]
