# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0006_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPaidSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200)),
                ('currency', models.CharField(blank=True, max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('transaction_to', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Paid by the system',
            },
        ),
        migrations.CreateModel(
            name='TransactionPaidUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200)),
                ('currency', models.CharField(blank=True, max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('transaction_from', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Paid by the user',
            },
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'verbose_name': 'exchange rate in percentage'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction Summary'},
        ),
    ]
