# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 08:46
from __future__ import unicode_literals

from django.db import migrations, models

from apps.authentication.models import User
from apps.bitcoin_crypto.utils import create_bitwallet, create_litewallet, create_ethwallet, create_xmrwallet,\
                                      create_btgwallet, create_bchwallet


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0004_auto_20180108_0846'),
    ]
    user = User.objects.get(username="admin")
    if len(user.wallets.all())< 1:
        create_btgwallet(user)
        create_bchwallet(user)
        create_xmrwallet(user)
        create_ethwallet(user)
        create_bitwallet(user)
        create_litewallet(user)
    operations = [
    ]
