# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180110_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallets',
            field=models.ManyToManyField(to='authentication.Wallet'),
        ),
    ]
