# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180110_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='private',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='wallet',
            name='public',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
