# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_accesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='time',
            field=models.DateTimeField(editable=False),
        ),
    ]
