# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20180202_0705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Admin Wallet'},
        ),
    ]
